### ISSUE TITLE
Add paths for niagara, gpc-penn and dirac

### ISSUE THREAD

**Issue by msyriac** [simonsobs/sofind#3]

**Comment by zatkins2** [comment]
Added instructions for how to add systems to `sofind` https://github.com/simonsobs/sofind/commit/1f1afbeb88f3f39cd730fd0d7f583cb65b3b2505

Actually adding the products to niagara, gpc-penn, and dirac, should be done by someone who wants to help manage products there, and then they would perform the steps listed there (the steps take 30 seconds, actually adding the data takes longer).
